### ISSUE TITLE
14-move auth route

### ISSUE THREAD

**Issue by AlessandroSaba1991** [AlessandroSaba1991/laravel-teams-comics#22]
-in providers/routeserviceprovider.php da /home a /admin
- creare rotte middleware 
- spostare  rotta home in middleware
- e modificare nome da home a dashboard
- spostare homeController fix namespace add use controller
- e modificare metodo index con rotta giusta
- implementare rotta any

**Comment by Fabiofljf** [comment]
faccio io!

**Comment by Fabiofljf** [comment]
fatto , controlla
