### ISSUE TITLE
8- develop Admin/CharactersController Sez.1

### ISSUE THREAD

**Issue by AlessandroSaba1991** [AlessandroSaba1991/laravel-teams-comics#8]
- develop index and destroy method
- develop view index

**Comment by Fabiofljf** [comment]
Faccio io!

**Comment by Fabiofljf** [comment]
1. Ho aggiunto nel controller index (file esterno , non in cartella) perciò la rotta è view('characters.index');
2. Ho aggiunto anche il delete sempre nel controller;
3. ho sviluppato la view di character html (sviluppata con la colonna);
4.  implementato lato html il metodo destroy dentro index --! Attenzione sistemare rotte show e edit!
5. Adesso controllo se va il ciclo.
